In [5]:
import numpy as np

print("MULTIPLICACION DE MATRICES")

n1=int(input("Ingrese el tamaño de la fila de la primera matriz: "))
m1=int(input("Ingrese el tamaño de la columna de la primera matriz: "))
matriz1 = np.ones((n1,m1))

for i in range(0,n1,1):
    for j in range(0,m1,1):
        matriz1[i][j]=int(input("ingrese el numero en la posicion ["+str(i)+"] ["+str(j)+"] : "))
        
print(matriz1)

n2=int(input("Ingrese el tamaño de la fila de la segunda matriz: "))
m2=int(input("Ingrese el tamaño de la columna de la segunda matriz: "))
matriz2 = np.ones((n2,m2))

for i in range(0,n2,1):
    for j in range(0,m2,1):
        matriz2[i][j]=int(input("ingrese el numero en la posicion ["+str(i)+"] ["+str(j)+"] : "))
        
print(matriz2)

matriz3 = matriz1.dot(matriz2)

print("La matriz resultante de la multiplicación de las dos matrices es la siguiente: ")
print(matriz3)

MULTIPLICACION DE MATRICES
Ingrese el tamaño de la fila de la primera matriz: 3
Ingrese el tamaño de la columna de la primera matriz: 2
ingrese el numero en la posicion [0] [0] : 1
ingrese el numero en la posicion [0] [1] : 2
ingrese el numero en la posicion [1] [0] : 3
ingrese el numero en la posicion [1] [1] : 4
ingrese el numero en la posicion [2] [0] : 5
ingrese el numero en la posicion [2] [1] : 6
[[1. 2.]
 [3. 4.]
 [5. 6.]]
Ingrese el tamaño de la fila de la segunda matriz: 2
Ingrese el tamaño de la columna de la segunda matriz: 3
ingrese el numero en la posicion [0] [0] : 1
ingrese el numero en la posicion [0] [1] : 2
ingrese el numero en la posicion [0] [2] : 3
ingrese el numero en la posicion [1] [0] : 4
ingrese el numero en la posicion [1] [1] : 5
ingrese el numero en la posicion [1] [2] : 6
[[1. 2. 3.]
 [4. 5. 6.]]
La matriz resultante de la multiplicación de las dos matrices es la siguiente: 
[[ 9. 12. 15.]
 [19. 26. 33.]
 [29. 40. 51.]]
